version: "3.9"

services:
  app:
    build:
      context: .
      args:
        - DEV=true
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    environment:
      - DB_HOST=db
      - DB_NAME=coditas_dot_ai
      - DB_USER=postgres
      - DB_PASS=password
    depends_on:
      - db
  db:
    image: postgres:13.13-alpine3.19
    volumes:
      - dev-db-data:/pg-docker-data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=coditas_dot_ai
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
volumes:
  dev-db-data:

